name: mt3-pytorch-env-38
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - protobuf==3.20.3
  - pip:
      - transformers==4.18.0
      - torch
      - librosa==0.9.1
      - ddsp==3.3.4
      - note-seq==0.0.3
      - pretty-midi==0.2.9
      - einops==0.4.1